# Generated by Django 5.2.11 on 2026-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_finance', '0002_remove_transaction_account_expense_userincome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='priority',
            field=models.CharField(default='Must Have', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='Burning', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
