# Generated by Django 5.2.11 on 2026-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_finance', '0004_userbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincome',
            name='calculation_method',
            field=models.CharField(default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='userincome',
            name='days_per_week',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userincome',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userincome',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userincome',
            name='is_hourly_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userincome',
            name='work_hours_per_month',
            field=models.IntegerField(default=160),
        ),
    ]
