// a code to generate a favicon.ico file from the PNG icons generated by generate-icons.js
// and run it with `node make-ico.js` from the Qeeva-Frontend root directory after running `node generate-icons.js` first
const pngToIcoModule = require('png-to-ico');
const pngToIco = pngToIcoModule.default || pngToIcoModule;
const fs = require('fs');

pngToIco([
  'public/icons/icon-16.png',
  'public/icons/icon-32.png',
  'public/icons/icon-48.png',
])
  .then(buf => fs.writeFileSync('public/favicon.ico', buf))
  .then(() => console.log('✓ favicon.ico — legacy fallback for Safari + old browsers'));
